#!/bin/bash
#
HISTFILE=$HOME/.cache/bash/history


files=(
        $HOME/.config/zsh/aliases.zsh 
        $HOME/.config/zsh/exports.zsh 
        $HOME/.config/bash/prompt
        )



for file in ${files[*]}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;


colorscript -r

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# *cd sin necesidad de escribir 'cd'
shopt -s autocd
